services:
  dock-shipmentcompany:
    build:
      context: .
      dockerfile: Dock-ShipmentCompany/Dockerfile
    ports:
      - "5283:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=dockdb;Database=dockdb;User=sa;Password=Your_password123!;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      dockdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  harbor-management:
    build:
      context: .
      dockerfile: HarborManagementService/Dockerfile
    ports:
      - "5282:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=harbordb;Database=HarborDb;User=sa;Password=Your_password123!;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      harbordb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  water-management:
    build:
      context: .
      dockerfile: WaterManagement/Dockerfile
    ports:
      - "5171:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=waterdb;Database=WaterDb;User=sa;Password=Your_password123!;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      waterdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  billing:
    build:
      context: .
      dockerfile: Billing/Billing/Dockerfile
    ports:
      - "5206:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=billingdb;Database=BillingDb;User=sa;Password=Your_password123!;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      billingdb:
        condition: service_healthy

  shipservice:
    build:
      context: .
      dockerfile: ShipService/ShipService/Dockerfile
    ports:
      - "5208:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=shipservicedb;Database=ShipServiceDb;User=sa;Password=Your_password123!;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      # billingdb:
      #   condition: service_healthy

  harbordb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  waterdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  billingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 10

  dockdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1437:1433"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'" ]
      interval: 10s
      timeout: 5s
      retries: 10

  shipservicedb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1438:1433"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
